"""Domain enums and workflow value objects."""

from dataclasses import dataclass
from enum import StrEnum


class WorkflowState(StrEnum):
    DISCOVERY = "DISCOVERY"
    WAITING_CONTEXT_INPUT = "WAITING_CONTEXT_INPUT"
    PLANNING = "PLANNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    IMPLEMENTING = "IMPLEMENTING"
    REVIEWING = "REVIEWING"
    COMPLETED = "COMPLETED"


class ArtifactType(StrEnum):
    CONTEXT = "CONTEXT"
    PLAN = "PLAN"
    APPROVAL = "APPROVAL"
    IMPLEMENTATION = "IMPLEMENTATION"
    REVIEW = "REVIEW"
    USER_CONTEXT_REQUEST = "USER_CONTEXT_REQUEST"
    USER_CONTEXT_RESPONSE = "USER_CONTEXT_RESPONSE"
    CONTEXT_REQUIREMENT = "CONTEXT_REQUIREMENT"


class ReviewVerdict(StrEnum):
    PASSED = "passed"
    FIX_REQUIRED = "fix_required"
    CONTEXT_REQUIRED = "context_required"


class ErrorCode(StrEnum):
    WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    INVALID_ARTIFACT = "INVALID_ARTIFACT"
    PLAN_NOT_FOUND = "PLAN_NOT_FOUND"
    PLAN_VERSION_MISMATCH = "PLAN_VERSION_MISMATCH"
    PLAN_NOT_APPROVED = "PLAN_NOT_APPROVED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    USER_CONTEXT_REQUIRED = "USER_CONTEXT_REQUIRED"
    CONTEXT_NOT_SUFFICIENT = "CONTEXT_NOT_SUFFICIENT"
    REVIEW_VERDICT_INVALID = "REVIEW_VERDICT_INVALID"
    VALIDATION_ERROR = "VALIDATION_ERROR"


@dataclass(frozen=True, slots=True)
class Workflow:
    workflow_id: str
    task: str
    state: WorkflowState = WorkflowState.DISCOVERY
    session_id: str | None = None
    project_path: str | None = None
